# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# set the default branch
# default: empty, the default branch on GitHub
branch: develop

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every day"

# search for requirement files
# default: True
# allowed: True, False
search: True

pr_prefix: "[PATCH]"

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
requirements:
    - requirements.txt:
        update: all
        pin: true
    - requirements_dev.txt:
        update: all
        pin: true

