name: Automatic version bumping

on:
  push:
    branches:
      - develop

jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    name: Bump Version

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version
    - name: Bump Version
      run: |
        ./.github/bumpversion.sh
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     tags: true
