name: Sanity Checks for PRs

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Verify CHANGELOG is changed
      uses: tj-actions/verify-changed-files@v7.1
      id: verify-changed-files
      with:
        files: CHANGELOG.md

    - name: Check the PR title is correct
      uses: Slashgear/action-check-pr-title@1.0.0
      with:
        regex: '[MAJOR]|[MINOR]|[PATCH]' # Regex the title should match.