name: Sanity Checks

on:
  - pull_request
  - push

jobs:
  - uses: actions/checkout@v2

  - name: Verify CHANGELOG is changed
    uses: tj-actions/verify-changed-files@v7.1
    id: verify-changed-files
    with:
      files: CHANGELOG.md